version: '2'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes: 
        - /mnt/a/mysql:/var/lib/mysql
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER="haseong"
#      - MYSQL_PASSWORD="haseongpass"
#      - MYSQL_ROOT_PASSWORD="rootpass"
#      - MYSQL_ROOT_HOST="%"
        
  rocker:
    image: haseong/rocker-rstudio:v1.5
    container_name: rstudio 
    build:
      context: .
      dockerfile: ./rocker-rstudio/Dockerfile
    volumes:
      - /mnt/a/:/home/rstudio/a
      - /mnt/a/home:/mnt/a/home
    stdin_open: true
    ports:
        - 8787:8787
    environment:
      PASSWORD: "dnjfvhgksrnr12"
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    


