FROM continuumio/miniconda3

RUN apt-get update \
    && apt-get install -y vim wget locales \
    cmake build-essential gcc g++ git libgl1-mesa-glx
#RUN locale-gen ko_KR.UTF-8
#ENV LC_ALL ko_KR.UTF-8

RUN conda config --set ssl_verify no
#RUN conda create -n dl python=3.6 openssl
#RUN /bin/bash -c "source activate dl"  \
RUN conda config --add channels conda-forge \
    && conda config --add channels anaconda \
    && conda config --add channels bioconda \
    && conda install biopython jupyterlab pandas matplotlib blast scikit-learn

RUN conda update -n base -c defaults conda
RUN conda install openssl certifi cffi scikit-image
RUN pip install torch 
RUN pip install torchvision

RUN apt-get install -y ca-certificates ssl-cert unzip

RUN pip install seaborn

# clean
RUN apt-get autoremove -y \
    && apt-get clean \
    && conda clean -i -l -t -y \
    && rm -rf /usr/local/src/*

ENV PATH /opt/conda/envs/env/bin:$PATH

#WORKDIR /work

