FROM mongo:6.0.4

#EXPOSE 27027

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
  curl \
	make \
  vim 

#RUN locale-gen ko_KR.UTF-8
#ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

#RUN echo "alias ll='ls -al'" >> ~/.bashrc


